require 'mechanize'
require "rest_client"
require 'pry-nav'
require 'nokogiri'
require 'csv'

class TownScraper 
	attr_reader :ids, :table
	def get_ocd_ids
		page = RestClient.get("https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/master/identifiers/country-us/census_autogenerated/us_census_places.csv")
		noko = Nokogiri::HTML(page)
		@ids = noko.text.lines.select do |line| #
			line =~ /state:il/
		end.reject do |line|
			line =~ /place:/
		end.map do |line|
		  line.gsub(/,.+/, '').gsub(/\n/, '')
		end 
	end 
	def get_all_jurisdictions
		agent = Mechanize.new
		page = agent.get("http://www.elections.il.gov/ElectionAuthorities/ElecAuthorityList.aspx?Selected=Election+Authorities")
		agent.page.parser.css('select').children[3].select
		form = agent.page.forms[0]
		form.field_with(:name=>"ctl00$ContentPlaceHolder1$ddlCounty").options[1].click
		@table = form.submit.parser.css('#ctl00_ContentPlaceHolder1_tblAllJuris')
	end
	def merge_into_new_rows
		rows = table.css('tr').drop(1).map do |tr|
			tds = tr.css('td')
			jurisdiction = tds[0].text
			title = tds[2].text
			phone_number = tds[5].text
			if tds[0].css('a').length > 0
				website = tds[0].css('a').attr('href').value
			else
				website = ""
			end
			id = @ids.find do |i|
				i =~ /#{jurisdiction}/i
			end || ""
			[jurisdiction,title,phone_number,website,id]
		end
	end

	def write_into_CSV_file
		CSV.open("spreadsheet.csv", "wb") do |csv|
			merge_into_new_rows.map do |line|
				csv << line
			end
		end
	end

end

a = TownScraper.new
a.get_ocd_ids
a.get_all_jurisdictions
a.merge_into_new_rows
a.write_into_CSV_file

